// <auto-generated />
namespace Vidly_Video_Rental_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetGenreIdColumnNotNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetGenreIdColumnNotNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202402092005496_SetGenreIdColumnNotNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
