// <auto-generated />
namespace Vidly_Video_Rental_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetNameOfMovieRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNameOfMovieRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202401300022517_SetNameOfMovieRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
